spring.application.name=backend

spring.datasource.url=jdbc:mysql://root:XdLKFNYZbyXatDlKkxaQjIKtTnIlumbI@zephyr.proxy.rlwy.net:48648/railway?useSSL=false&serverTimezone=Asia/Taipei
spring.datasource.username=root
spring.datasource.password=XdLKFNYZbyXatDlKkxaQjIKtTnIlumbI

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect